# We create empty UTMP_FILE and WTMP_FILE
mkdirp 0755 /var/run
touch  0664 /var/run/utmp.v2
touch  0664 /var/run/wtmp.v2
# Same for the old files as well
touch  0664 /var/run/utmp
touch  0664 /var/run/wtmp
# For default UTMP_FILE we need to create the lock files
mkdirp 0755 /var/lock
touch  0664 /var/lock/utmp.v2.lock
touch  0664 /var/lock/wtmp.v2.lock
touch  0664 /var/lock/utmp.lock
touch  0664 /var/lock/wtmp.lock

# Must run localedef as root to write into default paths.
su
